[Desktop Entry]
Name=Warmth
Type=X-GNOME-Metatheme
Comment=A smooth, blended theme for GTK.

[X-GNOME-Metatheme]
GtkTheme=Warmth
MetacityTheme=Warmth
IconTheme=Humanity-Dark
GtkColorScheme=fg_color:#222222,bg_color:#E4DBD2,base_color:#f5f5f5,text_color:#292929,selected_bg_color:#BC8A4B,selected_fg_color:#f5f5f5,tooltip_bg_color:#ffeebb,tooltip_fg_color:#333333
CursorTheme=Human
CursorSize=18
NotificationTheme=ubuntu
