[Desktop Entry]
Name=warmth_mk
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Wasp
MetacityTheme=Wasp
IconTheme=ubuntu-mono-light
GtkColorScheme=fg_color:#101010101010,bg_color:#d999ceb8ceb8,text_color:#1a1a1a1a1a1a,base_color:#ffffffffffff,selected_fg_color:#33332e5628e7,selected_bg_color:#b333a148a148,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#29a700001d0f
CursorTheme=DMZ-Black
CursorSize=24
NotificationTheme=ubuntu
